config/routes.rb
Gossiply::Application.routes.draw do
  get "sessions/create"
  get "sessions/destroy"

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  match '/users/friends/:id', to:'users#friends', via: 'get'
  match '/home', to:'generic_pages#home', via:'get'

  root 'generic_pages#index'
  resources :users
  resources :posts, dependent: :destroy

  

end

app/models/mention.rb
class Mention < ActiveRecord::Base
	belongs_to :user, foreign_key: :uid
	belongs_to :post
end

app/models/post.rb
include ActionView::Helpers
class Post < ActiveRecord::Base
	default_scope -> { order('created_at DESC') }
	belongs_to :user
	has_many :mentions
	has_many :mentioned_users, through: :mentions, source: :user

	validates :text, presence: true, length: {maximum:130}
	attr_accessor :mentioned

	  def as_json(options={})
  		{ :text => self.text, :sentiment => self.sentiment, :mentioned => self.mentions.first.uid, :created_at => time_ago_in_words(self.created_at)}
	end




end

app/models/user.rb
class User < ActiveRecord::Base
  self.primary_key = :uid
  has_many :posts
  has_many :mentions, foreign_key: :uid
  has_many :mentioned_posts, through: :mentions, source: :post, foreign_key: :uid


  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception, only: :delete
  before_filter :allow_cross_domain_access
    def allow_cross_domain_access
       response.headers["Access-Control-Allow-Headers"] = "Content-Type, X-Requested-With"
        response.headers["Access-Control-Allow-Methods"] = "GET, PUT, POST, DELETE"
        response.headers["Access-Control-Allow-Origin"] = "*"
    end

  private
	  def current_user
	  	if session[:user_id]
		    @current_user ||= User.find(session[:user_id])
		else
			@current_user = nil
		end
	  end
	  def signed_in_user
	  	if current_user.nil?
	  		redirect_to root_url
	  	end
	  end
	  helper_method :current_user
	  helper_method :signed_in_user
  
end

app/controllers/generic_pages_controller.rb
class GenericPagesController < ApplicationController
	def home
		if current_user
		 @graph = Koala::Facebook::API.new(current_user.oauth_token) 

		 @rest = Koala::Facebook::API.new(current_user.oauth_token)
		end
		 


	end
	def index
		if current_user
			redirect_to home_path
		end
	end
end

app/controllers/mentions_controller.rb
class MentionsController < ApplicationController

	def index
		@men = Mention.all
	respond_to do |format|
      format.json { render :json => @men }
   	 end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'open-uri'
require 'json'

	def create
    @post = current_user.posts.build(micropost_params)
    safe_text = params[:post][:text].gsub(/\s/,'%20')
    response = HTTParty.get("http://api.datumbox.com/1.0/SentimentAnalysis.json?api_key=a58c154d6ab8e1b4a0d69590668591d7&text=#{safe_text}")
    body = JSON.parse(response.body)
    result = body["output"]["result"]
    @post.sentiment = result
      

    
    if @post.save
      myid = params[:post][:mentioned]
         mention = Mention.new(uid: myid,post_id: @post.id )
         mention.save
        redirect_to @post
    else
      redirect_to root_url
    end
  end

  def show
    @post = Post.find params[:id]
    @rest = Koala::Facebook::API.new(current_user.oauth_token)
  end
  def new
    @graph = Koala::Facebook::API.new(current_user.oauth_token) 
    @profile = @graph.get_object("me")
    @post = current_user.posts.build
  end

  def destroy
    @post = Post.find params[:id]
    mentions = Mention.where(post_id:@post.id)
    mentions.each do |mention|
      mention.destroy
    end
    @post.destroy
    redirect_to current_user
  end
  def index
    @posts = Post.all
    @posts.each do |p|
      p.mentioned = p.mentions.first.uid
    end

     respond_to do |format|
      format.json do
        render :json => @posts.to_json(except: :user_id, :include => { :mentions => { :only => :uid } })
      end
    end
    
  end


  private



    def mention_params
      params.require(:post).permit(:mentioned)
    end

  	def micropost_params

  		params.require(:post).permit(:text)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@graph = Koala::Facebook::API.new(@user.oauth_token) 
		@profile = @graph.get_object("me")
		@post = current_user.posts.build
	end

	def index
		@users = User.all
		respond_to do |format|
			format.json { render :json => @users }
		end
	end

	def friends
		@user = User.find(params[:id])
		@graph = Koala::Facebook::API.new(@user.oauth_token) 
		@friends = @graph.get_connections("me", "friends")
		@friends.each do |friend|
			 friend[:image]= "http://graph.facebook.com/#{friend['id']}/picture?height=100&width=100"
		end
		respond_to do |format|
			format.json { render :json => @friends }
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/generic_pages_helper.rb
module GenericPagesHelper
end

app/helpers/mentions_helper.rb
module MentionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def getName(uid)
		return User.find(uid).name
	end

end

app/views/generic_pages/home.html.erb
<% if current_user %>

<% profile = @graph.get_object("me") %>
<% friends = @graph.get_connections("me", "friends") %>
<% friends_id_array = [] %>
<% friends.each do |friend| %>
  <% friends_id_array << friend["id"]  %>
 <% end %>
 <% friends_id_array << current_user.uid  %>

 <% feed_posts = Post.find_all_by_user_id(friends_id_array,limit: 30) %>


<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]> <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]> <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]> <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> 
<html lang="en" class="no-js"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title>Whisperer - Anonymous Gossip</title>

<!-- SEO -->
<meta name="description" content="Effortless event management software for online registration, check-in, nametags, surveys, and more.">
       <meta name="viewport" content="width=device-width">

       <!-- Social sharing -->
<meta property="og:type" content="website">
<meta property="og:title" content="post" />
<meta property="og:description" content="gossip" />
<meta property="og:image" content="person FB photo" />

<!-- CSS & Fonts -->
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700' rel='stylesheet' type='text/css'>

       <link rel="stylesheet" href="css/master.css" />

       <!-- Favicon -->
       <link rel="icon" href="images/favicon.ico" type="image/x-icon" />

       <!-- Javascript -->
               <%= javascript_include_tag "post_create" %>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
      <script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js" type="text/javascript"></script>
      <%= javascript_include_tag "bootstrap" %>
        <%= javascript_include_tag "modernizr-2.6.2-respond-1.1.0.min" %>

   </head>
   <body>


   	<!-- white content area -->
   	<div class="content_area">

   	<!-- title and subtitle -->
   	<div class="container">

   	<% feed_posts.each do |post| %>
   		<div class="row stream_row <%= post.sentiment %>">

     <!-- post -->
     <div class="col-md-7 stream_post">
     "<%= post.text %>"
     </div>

     <!-- person & sharing -->
     <div class="col-md-5">

     <!-- person -->
     <div class="post_box_person_stream">
                           <!-- photo -->
                           <div class="pull-left">
                           	<% if post.mentions.any? %>
                            <% my_query = "SELECT name FROM profile WHERE id = #{post.mentions.first.uid}"%>
                           		<%= image_tag "http://graph.facebook.com/#{post.mentions.first.uid}/picture?height=100&width=100", class: "img_face img-circle img-responsive" %>
                           	<% else %>
                           	 <%= image_tag "123.jpg", class:"img_face img-circle img-responsive" %>
                           	<% end %>
                               
                           </div>
                           <div class="pull-left">
                              <div class="post_caption">
                               posted about
                              </div>
                              <div class="post_name">
                                <%= @rest.fql_query(my_query)[0]["name"] %>
                              </div>


                              <div class="post_date">
                               Posted <%= time_ago_in_words(post.created_at) %> ago
                              </div>
                           </div>
                           <div class="clearfix"></div>
                       </div>

                       <div style="margin-top:25px;">
                         <button type="button" class="btn btn-danger" id="cta_share_twitter">
                                   <i class="fa fa-twitter"></i> tweet
                               </button>

                               <button type="button" class="btn btn-info" id="cta_share_facebook">
                                   <i class="fa fa-facebook"></i> share
                               </button>
                       </div>

     </div>
     </div><!-- end stream row -->

   	<% end %>

   	</div><!-- close container - title and subtitle -->
   </div><!-- close content area -->


   </body>
 </html>









<% end %>

app/views/generic_pages/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]> <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]> <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]> <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> 
<html lang="en" class="no-js"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title>Whisperer - Anonymous Gossip</title>

<!-- SEO -->
<meta name="description" content="Effortless event management software for online registration, check-in, nametags, surveys, and more.">
       <meta name="viewport" content="width=device-width">

       <!-- Social sharing -->
<meta property="og:type" content="website">
<meta property="og:title" content="post" />
<meta property="og:description" content="gossip" />
<meta property="og:image" content="person FB photo" />

<!-- CSS & Fonts -->
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="font-icons/css/font-awesome.min.css">
<link rel="stylesheet" href="bootstrap/css/bootstrap.css">
       <link rel="stylesheet" href="css/master.css" />

       <!-- Favicon -->
       <link rel="icon" href="images/favicon.ico" type="image/x-icon" />

       <!-- Javascript -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
   <script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js" type="text/javascript"></script>
       <script src="bootstrap/js/bootstrap.js"></script>
       <script src="javascript/modernizr-2.6.2-respond-1.1.0.min.js"></script>

   </head>
   <body>

   	

   	<!-- white content area -->
   	<div class="content_area">

   	<!-- title and subtitle -->
   	<div class="container">

   	 <!-- title -->
   	 <div class="row">
   	 <div class="col-md-12" id="home_title">
   	 post anonymously
   	 </div>
   	 </div>

   	 <!-- subtitle -->
   	 <div class="row">
   	 <div class="col-md-12" id="home_subtitle">
   	 about your friends
   	 </div>
   	 </div>

   	 <!-- CTA - sign up -->
   	 <div class="row">
   	 <div class="col-md-12" id="home_signup">

     <%= link_to "Sign in", "/auth/facebook", id: "cta_home_signup", class: "btn btn-success" %>
   	 <div id="home_signup_hint">
   	 all the cool kids are doing it.
   	 </div>
   	 </div>
   	 </div>
   	</div><!-- close container - title and subtitle -->
   </div><!-- close content area -->

   	
   </body>
 </html>

app/views/layouts/_footer.html.erb
   	<!-- footer -->
   	<div id="footer">
   	 <div class="container">
   	 <div class="row">
   	 <div class="col-md-12">
   	 created at the <a href="http://www.hackbeanpot.com" target="_blank">Beanpot Hackathon</a> by John Kohler, Lukas Berger & Greg Skloot
   	 </div>
   	 </div>
   	 </div>
   	</div>

app/views/layouts/_header.html.erb
<!-- top bar - purple -->
    <div id="topbar_purple">
     <div class="container">
     <div class="row">
     <div class="col-md-12">

     <!-- logo -->
     <div class="pull-left">
     <a href="<%= root_url %>">
         <%= image_tag "logo.png" %>
                           </a>
     </div>
     <!--style="margin-right:10px;" -->
     <% if current_user %>
     <!-- log in / out -->
     <div class="pull-right" id="login">
     <%= link_to('post',new_post_path,style:"margin-right:10px;") %>
     <%= link_to('me',current_user,style:"margin-right:10px;") %>
     <%= link_to('friends',home_path,style:"margin-right:10px;") %>
     <%= link_to "sign out", signout_path, id: "sign_out" %>
     </div>
     <% else %>
     <div class="pull-right" id="login">
     <%= link_to "Sign in", "/auth/facebook", id: "sign_in" %>
 </div>

     <% end %>
     </div>
     </div><!-- end row -->
     </div><!-- end container --> 
    </div><!-- end top bar purple -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whisperer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]> <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]> <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]> <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> 
<html lang="en" class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Whisperer - Anonymous Gossip</title>

    <!-- SEO -->
    <meta name="description" content="Effortless event management software for online registration, check-in, nametags, surveys, and more.">
        <meta name="viewport" content="width=device-width">

        <!-- Social sharing -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="post" />
    <meta property="og:description" content="gossip" />
    <meta property="og:image" content="person FB photo" />

    <!-- CSS & Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="font-icons/css/font-awesome.min.css">
    <link rel="stylesheet" href="bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="css/master.css" />

        <!-- Favicon -->
        <link rel="icon" href="images/favicon.ico" type="image/x-icon" />

        <!-- Javascript -->
        <%= javascript_include_tag "post_create" %>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
      <script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js" type="text/javascript"></script>
      <%= javascript_include_tag "bootstrap" %>
        <%= javascript_include_tag "modernizr-2.6.2-respond-1.1.0.min" %>


    </head>
    <body>

      <!-- white content area -->
        <div class="content_area" style="min-height:500px;">

        <!-- title and subtitle -->
        <div class="container">

          <!-- search box -->
          <!-- this should be hidden after a name is selected -->
          <div class="row input-search-box">
            <div class="col-md-12">
                        <!--<div class="post_search_names_help">
                            1. choose a friend to post about
                        </div>-->
              <div class="post_search_names">
                <input type="text" class="input_post_search_names" placeholder="type a friend's name">
              </div>
            </div>
          </div>

          <!-- box of names -->
          <div class="row input-search-suggest">
            <div class="col-md-12">
                        </div>
            </div>
          </div>
          <%= form_for(@post) do |f| %>
          <!-- input - create post -->
          <div class="row input-message">
            <div class="col-md-12">
              <div class="post_text">
                
                <%= f.text_area :text, placeholder: "Compose new post" , class: "input_post_text "%>
                            <div class="word-counter"></div>
                <input type="hidden" name="post[mentioned]" id="hidden_uid">
              </div>
            </div>
          </div>

          <!-- button - post -->
          <div class="row input-submit">
            <div class="col-md-12" id="home_signup">
              
              <%= f.submit "Post", class: "btn btn-success", id:"cta_home_signup" %>
              <% end %>
              <div id="home_signup_hint">
                don't worry, <!-- dynamic name --><span class="dyname">John </span> will never know it was you.
              </div>
            </div>
          </div>

        </div><!-- close container - title and subtitle -->
      </div><!-- close content area -->

    </body>
  </html>

  <script type="text/javascript">
  $(document).ready(function() {

    // handle friend input search
    var friends = [];

    $.getJSON('http://whisperer.herokuapp.com/users/friends/<%= current_user.uid %>.json',
            function(data) {
                friends = data;
            });

    $(".input_post_search_names").on("keyup", function () {
        var name = this.value;

        if (name.length < 3) {
            $('.input-search-suggest')[0].innerHTML = '';
        } else {
            results = find(name, friends);
            suggest(results, $('.input-search-suggest')[0]);
        }

    });

    $(".input_post_text").on("keyup keydown blur", function () {
        var name = this.value;

        if (name.length >= 130) {
            this.value = name.substring(0, 130);
        }

        $('.word-counter').text((130 - this.value.length) + ' out of 130 characters remaining');

    });

});

// find the given name in the list of tokens
var find = function (name, friends) {
    // the array of results
    var results = [];
    // serach the tokens for potential matches
    for (var i = 0; i < friends.length; i++) {
        // create a new regular expression, which will find the name
        var findname = new RegExp("\\b" + name + "[a-zA-Z]*",'i');
        // if the token is a substring
        var found = findname.exec(friends[i].name);
        // if we find the name add it to the results
        if (found !== null) results.push(friends[i]);
    }
    // return all the results
    return results;
};

// suggests matches based on the give array
var suggest = function (matches, suggestions) {
    // clear the suggestions box
    suggestions.innerHTML = '';
    // iterate through all the matches
    for (var i = 0; i < matches.length; i++) {
        // create a div element for every match
        var elem = document.createElement('div');
            elem.className = 'post_box_person_create person' + matches[i].id;
            elem.innerHTML = '<a href="#"><div class="pull-left"><img src="' + matches[i].image +'" class="img_face img-circle img-responsive"></div>' +
                    '<div class="pull-left"><div class="post_name_create">' + matches[i].name +
                    '</div></div><div class="clearfix"></div></div></a>';
          elem.onclick = slideSelect.bind(this, matches[i]);
        // add the div element to the suggestions
        suggestions.appendChild(elem);
    }
};

var slideSelect = function (match) {
    $('#hidden_uid').val(match.id)

    $('.input-search-box').animate({
        opacity: 0,
        'margin-top': '-200px'
     }, 300, function() {
        $('.input-message,.input-submit').fadeIn(300);
     });

    $('.input-search-suggest').animate({
        'margin-top': '150px'
     }, 300, function() {});

    $('.post_box_person_create:not(.person' + match.id + ')').animate({
        opacity: 0,
        height: 0,
        'margin-top': 0, 'margin-bottom': 0, padding: 0,
        overflow: 'hidden'
     }, 300, function() {
        this.remove();
     });

};

  </script>

app/views/posts/show.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]> <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]> <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]> <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> 
<html lang="en" class="no-js"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<title>Whisperer - Anonymous Gossip</title>

<!-- SEO -->
<meta name="description" content="Effortless event management software for online registration, check-in, nametags, surveys, and more.">
       <meta name="viewport" content="width=device-width">

       <!-- Social sharing -->
<meta property="og:type" content="website">
<meta property="og:title" content="post" />
<meta property="og:description" content="gossip" />
<meta property="og:image" content="person FB photo" />

<!-- CSS & Fonts -->
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="font-icons/css/font-awesome.min.css">
<link rel="stylesheet" href="bootstrap/css/bootstrap.css">
       <link rel="stylesheet" href="css/master.css" />

       <!-- Favicon -->
       <link rel="icon" href="images/favicon.ico" type="image/x-icon" />

       <!-- Javascript -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
   <script src="http://code.jquery.com/ui/1.8.21/jquery-ui.min.js" type="text/javascript"></script>
       <script src="bootstrap/js/bootstrap.js"></script>
       <script src="javascript/modernizr-2.6.2-respond-1.1.0.min.js"></script>

   </head>
   <body>


    <!-- white content area -->
    <div class="content_area">

    <!-- post text, person, social sharing -->
    <div class="container">

     <!-- post text -->
     <div class="row">
     <div class="col-md-12" id="post_text">
     "<%= @post.text %>"
     </div>
     </div>

               <!-- person box -->
               <div class="row">
                   <div class="col-md-12">
                       <div class="post_box_person">
                           <!-- photo -->
                           <div class="pull-left">
                            <% if @post.mentions.any? %>
                            <% my_query = "SELECT name FROM profile WHERE id = #{@post.mentions.first.uid}" %>
                              <%= image_tag "http://graph.facebook.com/#{@post.mentions.first.uid}/picture?height=100&width=100", class: "img_face img-circle img-responsive" %>
                            <% else %>
                             <%= image_tag "123.jpg", class:"img_face img-circle img-responsive" %>
                            <% end %>
                               
                           </div>
                           <div class="pull-left">
                              <% if @post.mentions.any? %>
                              <div class="post_caption">
                               posted about
                              </div>
                              <div class="post_name">
                               <%= @rest.fql_query(my_query)[0]["name"] %>
                              </div>
                              <% else %>
                                <div class="post_caption">
                               posted about
                              </div>
                              <div class="post_name">
                               ???
                              </div>

                              <% end %>
                              <div class="post_date">
                               <%= time_ago_in_words(@post.created_at) %> ago
                              </div>
                           </div>
                           <div class="clearfix"></div>
                       </div>
                   </div>
               </div>

                   <!-- social sharing buttons -->
                   <div class="row">
                       <div class="col-md-12">
                           <div class="post_box_social">
                               <button type="button" class="btn btn-danger" id="cta_share_twitter">
                                   <i class="fa fa-twitter"></i> tweet
                               </button>

                               <button type="button" class="btn btn-info" id="cta_share_facebook">
                                   <i class="fa fa-facebook"></i> share
                               </button>
                           </div>
                       </div>
                   </div>
               </div>

    </div><!-- close container -->
   </div><!-- close content area -->

   </body>
 </html>

app/views/users/index.html.erb
<div class="container">
<ul>
<% @users.each do |user| %>
	<li><%= user.name %></li>

<% end %>

</ul>
</div>

app/views/users/show.html.erb
<div class="container">
<h1>
	<img src="<%= @graph.get_picture(@profile["id"]) %>">
	<%= @profile["name"] %>
</h1>



</ul>

</div>